### ISSUE TITLE
Unable to auth with Docker Hub and private registries

### ISSUE THREAD

**Issue by gokhansengun** [rpardini/docker-registry-proxy#1]
Using registries with public images on (`registry-1.docker.io`, `gcr.io`, `quay.io`) everything is working great.

However setting up auth with Docker Hub or my own private hub results in with 401. Using `docker login` from the box where the HTTPS PROXY is defined also fails.

I wonder if it works for you and it is just me.

`http-proxy.conf` content

```
[Service]
Environment="HTTPS_PROXY=http://172.27.44.181:3128"
```

Command run:

```
docker run --rm --name docker_registry_proxy -it \
       -p 0.0.0.0:3128:3128 \
       -v $(pwd)/docker_mirror_cache:/docker_mirror_cache \
       -v $(pwd)/docker_mirror_certs:/ca \
       -e REGISTRIES="k8s.gcr.io gcr.io quay.io" \
       -e AUTH_REGISTRIES="registry-1.docker.io:gsengun:THE_PASS" \
       rpardini/docker-registry-proxy:latest
```

And here is the logs:

```
HIT [21/Jul/2018:00:25:14 +0000] "/v2/" 401 87 "HOST:registry-1.docker.io" "PROXY-HOST:registry-1.docker.io" "UPSTREAM:-"
HIT [21/Jul/2018:00:25:14 +0000] "/token" 200 4322 "HOST:auth.docker.io" "PROXY-HOST:auth.docker.io" "UPSTREAM:-"
MISS [21/Jul/2018:00:25:14 +0000] "/v2/gsengun/spring-demo-app/manifests/latest" 401 166 "HOST:registry-1.docker.io" "PROXY-HOST:registry-1.docker.io" "UPSTREAM:52.54.155.177:443"
```

I have tested with docker versions >= 17.03.0-ce

**Comment by rpardini** [comment]
Hi @gokhansengun thanks for the report and sorry for taking so long to look at this.
I do use a few private registries with auth and its working (its the whole point of this).

The thing is those registries are not the official DockerHub, but simple private registries hosted by myself.

I don't have a private/paid DockerHub account to test with, and it seems that this problem only affects that specific use case: from the logs you posted, it seems like docker goes both to `registry-1` as well as `auth`, both under `.docker.io`.

You could try adding some more hostnames to auth against, for example:

```bash
docker run --rm --name docker_registry_proxy -it \
       -p 0.0.0.0:3128:3128 \
       -v $(pwd)/docker_mirror_cache:/docker_mirror_cache \
       -v $(pwd)/docker_mirror_certs:/ca \
       -e REGISTRIES="k8s.gcr.io gcr.io quay.io" \
       -e AUTH_REGISTRIES="registry-1.docker.io:gsengun:THE_PASS auth.docker.io:gsengun:THE_PASS" \
       rpardini/docker-registry-proxy:latest
```

Could try that and post the logs again?

If that solves it, I could implement a way to avoid having to do it twice, or at least document that.

Thanks.

**Comment by manlme** [comment]
I met this problem too. it seems that token from auth.docker.io should not be cached. it will expire and cause such problem.

**Comment by rpardini** [comment]
Interesting. I will investigate ASAP.

**Comment by outworlder** [comment]
I am having trouble authenticating to Quay, not entirely sure the issue is related. Quay doesn't redirect to other URLs, it only uses /v2 and /v2/auth

```HIT [02/Nov/2018:18:50:16 +0000] "/v2/" 401 40 "HOST:quay.io" "PROXY-HOST:quay.io" "UPSTREAM:-"
HIT [02/Nov/2018:18:50:17 +0000] "/v2/auth" 200 1063 "HOST:quay.io" "PROXY-HOST:quay.io" "UPSTREAM:-"
MISS [02/Nov/2018:18:50:18 +0000] "/v2/<repository-redacted>/<image-name-redacted>/manifests/4.2.0-8" 401 40 "HOST:quay.io" "PROXY-HOST:quay.io" "UPSTREAM:50.16.237.72:443"
```

You'll see that /v2 is a HIT (401), /v2/auth is a HIT (200) (is it supposed to cache it?), but the image itself is a MISS 401.

Docker will say: `Error response from daemon: unauthorized: authentication required`

Pulling from public registries obviously works just fine, as does the caching.

**Comment by outworlder** [comment]
@rpardini Hi, I did test with 0.2.1, but it doesn't seem to have helped. For now, I can work around this by a) not providing authentication for quay.io to the proxy and b) keeping the auth information in docker, as the header is preserved by the proxy.
