### ISSUE TITLE
gcr.io - problem with service account

### ISSUE THREAD

**Issue by marcinkowalczuk** [rpardini/docker-registry-proxy#10]
Have you ever tested connecting to gcr.io private registry?
The content of service account contains many ":", and when you parse hostname, username and password you used "cut -d ":" -f x"

Maybe you have a way how to send the content of service account in this ENV? I don't have any idea :( I think that a better way will be sending password in base64. 

However everything works great with gcr.io, but I must set docker.auth.map manually. Thank you for good stuff.

**Comment by ptone** [comment]
Also related, the auth scope for a registry on gcr.io is more accurately captured as:

`[region].gcr.io/<project>`

Where region is optional part of hostname, and project is required.

There may be different auth values for different projects, all at gcr.io TLD

But yes - this is awesome work, I'm experimenting with running this as a kubernetes workload @rpardini reach out if this sounds interesting

**Comment by ptone** [comment]
I have a patched local version, which uses `|` instead of `:` but this alone would be a "breaking change".

How do you feel about that?  One approach would be to put in some regex test for gcr.io in the entrypoint loop of `for ONEREGISTRYIN in ${AUTH_REGISTRIES}; do`

**Comment by tiangolo** [comment]
I made a fix for this on #16. You might want to check it out and comment on the PR.

**Comment by tfriedel** [comment]
@tiangolo: thanks, this works!

while I can connecto gcr now, nothing is ever cached from there. images from docker hub are cached.

**Comment by rpardini** [comment]
@tiangolo Your patches were included in `0.3.0-beta1` -- we could try and see how it goes.

**Comment by rpardini** [comment]
Hmm, I'm gonna go ahead and close this.
