### ISSUE TITLE
Use Docker Proxy without a certificate

### ISSUE THREAD

**Issue by Ramhm** [rpardini/docker-registry-proxy#11]
Hi
I want to use this service mirroring the registry docker but without importing the certificate
So it's easy to download docker images kubernetes on Http
I need to cache all images .
is this possible?

**Comment by rpardini** [comment]
Not with this software. This one implements the caching using a man-in-the-middle which requires the certificate injection.
Docker Registry itself can serve as cache for the Docker hub, check that.
