### ISSUE TITLE
Storage usage with CACHE_MAX_SIZE var

### ISSUE THREAD

**Issue by angelsantillana94** [rpardini/docker-registry-proxy#117]
Hello,

I have a question about the `CACHE_MAX_SIZE` variable.

Once the occupied size equals `CACHE_MAX_SIZE` what
happens? Can more images be stored? is there some kind of rotation by date or similar?

Regardless of the above, is there a way to free up space? what would be the best option to save space?

Thanks,

Regards.

**Comment by rpardini** [comment]
Hi. CACHE_MAX_SIZE is directly passed to max_size= parameter of http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path
So please check nginx docs about it.
