### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by saada** [rpardini/docker-registry-proxy#119]
We deploy the `docker-registry-proxy:0.6.4` image to use as a local registry proxy. When pulling images from Docker Hub this image does not run correctly on ARM64 — the nginx worker process inside the container segfaults and the proxy returns 401 to all layer requests. The workaround is to clone the proxy and build it locally:

```
git clone https://github.com/rpardini/docker-registry-proxy
cd docker-registry-proxy
DOCKER_BUILDKIT=1 docker build .
```

Can we publish multi-arch docker images to support ARM as well?
Thank you for this awesome project!

**Comment by rpardini** [comment]
@saada - Funny. I run these exact images on ARM64 myself (they're multiarch enabled). Can you capture the errors and post them please?

**Comment by pratikbalar** [comment]
@rpardini i think i can create multi arch container image with CI

**Comment by rpardini** [comment]
Hmm. Nice, thanks.

**Comment by pratikbalar** [comment]
Actually we can create multi arch images but I'm finding solution to test those images in their respective arch
