### ISSUE TITLE
Gitlab Registry: unauthorized: authentication required

### ISSUE THREAD

**Issue by abtalerico** [rpardini/docker-registry-proxy#127]
Hello,

I'm getting an authorization error when trying to pull from registry.gitlab.com. The credentials I'm using work perfectly for authing to registry.gitlab.com on my local machine, so I'm guessing it has something to do with GitLab and the proxy interacting.

```{"access_time":"27/Jan/2022:15:04:10 +0000","upstream_cache_status":"MISS","method":"GET","uri":"/v2/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-e0218c92","request_type":"manifest-default-disabled","status":"401","bytes_sent":"188","upstream_response_time":"0.120","host":"registry.gitlab.com","proxy_host":"registry.gitlab.com","upstream":"35.227.35.254:443"}```

On clients this ends up looking like:

```Error response from daemon: unauthorized: authentication required```

Any help or insight into why this is happening would be appreciated.

**Comment by rpardini** [comment]
Sure, https://github.com/rpardini/docker-registry-proxy#gitlab-auth

**Comment by abtalerico** [comment]
Whoops, sorry for missing that! Thanks.
