### ISSUE TITLE
Question: how to use this amazing image with proxy peers

### ISSUE THREAD

**Issue by fpizzo20** [rpardini/docker-registry-proxy#132]
Good morning,

i've a strange use-case for this caching registry: i need to cache images that are already served by another squid proxy.

The net layout is:
- ECR docker registry, configured as private in VPC-net only
- A nginx server configured to perform auth to ECR and forward all requestes (in VPC)
- A Squid proxy server (in PVC) in front of nginx 
- A VPN connection with 1-to-1 NAT mappings
- This image in a on-premise server, that need to pull images from ECR repo

My need is to use my already running SQUID server as peer, so all the http requestes are redirected to that proxy
I must use this server beacuse the nginx server on front of ECR is behind a Application load balancer that has dynamic IP address, and it is impossible to map a dynamic IP address in the 1-to-1 NAT used at the VPN border.

Can you explain how to configure (if possible) the embedded proxy to use another proxy as a peer??

Thank you in advance
Have a nice weekend
Frank

**Comment by rpardini** [comment]
Hello Frank, I don't think I can help you in the scope of this open-source, freely contributed project. You mention a very complex, very enterprise use case, involving multiple proxies. Although theoretically doable, it would involve multiple man-in-the-middle certificate injections. There is no "peering" possible in the squid sense. This would be a brittle setup and would require constant maintenance.
