### ISSUE TITLE
Can S3 be used and main storage?

### ISSUE THREAD

**Issue by shellshock1953** [rpardini/docker-registry-proxy#141]
Hi, 
Can docker-registry-proxy use S3 as a storage backend?
S3 has the ability, for example. to delete "old" files (cache, in this scope) after some time (and others). In this scenario, you don't need to administrate disk space anymore.

**Comment by rpardini** [comment]
Ehh... this project uses `nginx`'s caching, which is on a filesystem. You can try the old hacks, but I really don't recommend it. Maybe EFS is more appropriate, but check the nginx docs.
