### ISSUE TITLE
Add ghcr.io to the default list of cached registries

### ISSUE THREAD

**Issue by deviantintegral** [rpardini/docker-registry-proxy#151]
I was confused why GitHub Container Registry images weren't caching, until I realized that it's neither default like Docker Hub nor in the default copy-paste list in the README. Is there any reason to not cache ghcr containers by default?

**Comment by rpardini** [comment]
ghcr.io (and other recent registries) have not been tested/made to work _at all_ with this, much less made default.

**Comment by deviantintegral** [comment]
Sounds good, thanks for the response.

I’m using ghcr.io and it’s been working fine for the last few days, except for an IPv6 issue I commented on at https://github.com/rpardini/docker-registry-proxy/pull/142. I’m not pushing images though. If there’s anything in particular you’d like me to test or watch out for, I’m glad to do so.

**Comment by LachlanStone** [comment]
Hi @deviantintegral ,

Can you provided you configuration for caching ghcr.io as I can't seem to get mine working

**Comment by deviantintegral** [comment]
I have:

- `REGISTRIES=k8s.gcr.io gcr.io quay.io lscr.io ghcr.io cr.fluentbit.io` in my docker compose environment config.
- No authentication as it doesn't seem to be working.

... and that's it! I just checked by pulling / removing / pulling an image, and it was returned by the cache.

**Comment by LachlanStone** [comment]
@deviantintegral 

Thank you for the update, I will test this on my end

**Comment by adrianipopescu** [comment]
did anyone got lscr working?
