### ISSUE TITLE
Authorization Problem with harbor registry

### ISSUE THREAD

**Issue by christianknell** [rpardini/docker-registry-proxy#19]
Hi there,
when pulling an image from my private harbor registry i get a 
`Error response from daemon: unauthorized: authentication required`
 on the cache client. 

The `docker-registry-proxy` logs say the following:

> [03/Sep/2019:17:18:48 +0000] "/v2/" 401 87 "HOST:MY_HARBOR_REGISTRY" "PROXY-HOST:MY_HARBOR_REGISTRY" "UPSTREAM:IP_OF_MY_HARBOR_REGISTRY:443"
> [03/Sep/2019:17:18:48 +0000] "/service/token" 200 978 "HOST:MY_HARBOR_REGISTRY" "PROXY-HOST:MY_HARBOR_REGISTRY" "UPSTREAM:IP_OF_MY_HARBOR_REGISTRY:443"
> [03/Sep/2019:17:18:48 +0000] "/v2/transmart/transmart/manifests/1.0.0" 401 162 "HOST:MY_HARBOR_REGISTRY" "PROXY-HOST:MY_HARBOR_REGISTRY" "UPSTREAM:IP_OF_MY_HARBOR_REGISTRY:443"

But the Authentication seems to be configured as the logs say:
`Adding Auth for registry 'MY_HARBOR_REGISTRY' with user 'christian.knell'.`

The same behaviour when trying to pull a public repository or even when doing
`docker login MY_HARBOR_REGISTRY`

**Comment by rpardini** [comment]
Could you try with `0.3.0-beta1` and report back? Thanks!

**Comment by rpardini** [comment]
No way to reproduce, and no feedback, closing...
