### ISSUE TITLE
setup docker-registry-proxy image to proxy request to no standard port

### ISSUE THREAD

**Issue by mbaesso** [rpardini/docker-registry-proxy#21]
Hi,
i would like to know if is possible to use this image to proxy request to https:registry:5000 and what we need to change in order to satisfy this goal
thanks in advance

Mirko

**Comment by raffis** [comment]
Any plans for this one?

**Comment by rpardini** [comment]
Hello, no, there is no support for such.
I suggest you first expose your :5000 server via HTTPS on port 443 using other means (reverse proxy, etc)
Then you can consider using this as a caching layer.
