### ISSUE TITLE
update failed packages

### ISSUE THREAD

**Issue by gattytto** [rpardini/docker-registry-proxy#24]
hello, so far this registry proxy suits my needs with only 1 pitfall that I found a quick workaround for:
pull failed because a host wasn't included in the "docker run" command, but then I don't want to loose my downloaded stuff. 

At the point of this failure I'm using the proxy to cache Ecliipse-Che images which are downloaded from many sources, first time I forget to include cloudflare to the list and I get "invalid URL signature" when a che workspace is being built from a factory devfile.

the workaround:
I stop the daemonized registry proxy I was running (using the -d command in addition  to the one suggested in the readme), add the missing repo URL to my docker run command, use a different folder for the images cache (a previously created empty folder) and use the same ca folder as before.

empty cache folder will start getting filled with images after I do "docker pull some-registry.io/failing-package:latest" (from the client configured to use the registry proxy as images source)

once this process is done and the cache has all  the downloaded new images, copy the contents from the new cache folder to the old cache folder.

finally fix permissions: chown -R messagebus:root /the-cache-folder

now stop the running registry-proxy again

run my docker-registry-proxy cache as always with -d to leave running as daemon and bring back the original cache folder with the new content copied over it. 

now stuff works, I have my whole cache without needing to redownload it, and new content has been provisioned to it the right way.

cheers and thanks for your effort this is very helpful for slow bandwidths and big apps (like che)

**Comment by rpardini** [comment]
Hmm. Interesting to know. Thanks.
