### ISSUE TITLE
Hostname not properly set :/

### ISSUE THREAD

**Issue by Mechtecs** [rpardini/docker-registry-proxy#3]
Somehow the nginx cache fails to set the hostname properly. This prohibits this cache to function in a reverse proxied docker registry scenario.

I will submit a PR with my fix.

**Comment by Mechtecs** [comment]
Specific error:
`
2018/09/27 16:35:06 [error] 113#113: *3 upstream SSL certificate does not match "..." while SSL handshaking to upstream, client: 127.0.0.1, server: _, request: "GET /v2/ HTTP/1.1", upstream: "https://...:443/v2/", host: "..."
MISS [27/Sep/2018:16:35:06 +0000] "/v2/" 502 173 "HOST:..." "PROXY-HOST:..." "UPSTREAM:...:443"
2018/09/27 16:35:06 [error] 113#113: *8 upstream SSL certificate does not match "..." while SSL handshaking to upstream, client: 127.0.0.1, server: _, request: "GET /v2/.../.../manifests/master HTTP/1.1", upstream: "https://...:443/v2/.../.../manifests/master", host: "..."
`

**Comment by rpardini** [comment]
This is actually a feature, we check upstream's certificates to avoid man-in-the-middle attacks.
Funny, since this is actually a man-in-the-middle implementation.
You can disable it by passing an env var `VERIFY_SSL=false`.
