### ISSUE TITLE
Looks like the multiple client request cache locking is not working

### ISSUE THREAD

**Issue by timorkal** [rpardini/docker-registry-proxy#31]
Hello, I've tested pulling from multiple docker client machines the same image (2GB) at the same time through the registry proxy.
As stated in the nginx.conf it should do the "proxy_cache_lock on" feature, which suppose to download the blob/image from the origin only once, but instead it downloads it multiple times as per clients requests.
With only 1 client it took 1:43 minutes to download and distribute.
With 2 clients it took 3:05 minutes to download and distribute.
And with 4 clients it took 6:07 minutes to download and distribute.

Why do you think it works like that?

**Comment by rpardini** [comment]
No idea. I've updated nginx versions in `0.3.0-beta1`, maybe you could try that and see if it fixes it?

**Comment by rpardini** [comment]
No feedback. Closing.

**Comment by WeetA34** [comment]
Hello,
It seems you also have to configure [proxy_cache_lock_age](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_lock_age). Its default value is 5s.
