### ISSUE TITLE
why the log output is not in JSON 

### ISSUE THREAD

**Issue by naftulee** [rpardini/docker-registry-proxy#36]
running this in k8s works,  but most modern monitoring,data collecting prefer json and not just strings...

**Comment by rpardini** [comment]
Well, it's just nginx, you can configure the logging format. Send a PR!

**Comment by naftulee** [comment]
yes your totally right. I did something like this ... works just fine.  newish to nginx didnt realize it could be so simple before I posted. 

log_format tweaked escape=json
   '{'
   '"upstream_cache_status":"$upstream_cache_status",'
   '"access_time":"$time_local",'
   '"uri":"$uri",'
   '"status":"$status",'
   '"bytes_sent":"$body_bytes_sent",'
   '"host":"$host",'
   '"proxy_host":"$proxy_host",'
   '"upstream":"$upstream_addr"'
   '}';
