### ISSUE TITLE
Access to multiple private registries on one IP does not work

### ISSUE THREAD

**Issue by peterhaaf** [rpardini/docker-registry-proxy#37]
Hi,

i need to configure your lovely project to access multiple registries living on one IP Adress. 
Multiple means a lot in my usecase so best would be if the docker pull url could be interpreted:
Let me give you an example:

docker.local.foo.bar:50000/image1:latest
docker.local.foo.bar:50020/image1:latest
docker.local.foo.bar:50030/image1:latest
Authentication is however uniq ( at least for now) to the registry host ( docker.local.foo.bar) 

Unfortunately my nginx is limited, so any hint is highly appreciated.

Thanx
Peter

**Comment by rpardini** [comment]
Hmm. I don't think non-standard ports are supported, since we don't carry them over in the rewriting.
Try using name-based virtual hosts for your registries (docker1.local.foo.bar:443, docker2.local.foo.bar:443) and it should work.
