### ISSUE TITLE
Support of custom ports

### ISSUE THREAD

**Issue by Mechtecs** [rpardini/docker-registry-proxy#4]
Currently i see no way, the cache could be configured for the following host:

https://docker.xxx.xxx:5000

The support of custom ports should be implemented.

**Comment by rpardini** [comment]
You're right.
There's two problems with this:
1) The auth config uses ":" as separador (registry_host:username:password)
2) There's a huge chance that even if 1) was solved, you'd still need insecure registry support, which is not there.
