### ISSUE TITLE
Registry auth passthrough

### ISSUE THREAD

**Issue by peterhaaf** [rpardini/docker-registry-proxy#47]
Hi,

can you think of a way to pass the docker client auth data through the proxy cache ? 

The idea is, not to maintain this central authorization datafile, and leave the pull secret stuff, up to kubernetes

Any idea would be helpful.

Thanx 
Peter

**Comment by peterhaaf** [comment]
Hi,

i think i got this working by removing the two proxy_set_header statements in the caching layer section of the nginx.conf file. At least the tests i did where successful. 
Any remarks on this would be highly appreciated...

Thanx
Peter

**Comment by rpardini** [comment]
I'm sure there is a way, although the central auth configuration is considered a feature ;-) 
Try using only REGISTRIES env var (not AUTH_REGISTRIES).
Maybe you'll need to hack in the nginx config to avoid touching the Authorization header too.
