### ISSUE TITLE
modify nginx.conf to forward corporate proxy

### ISSUE THREAD

**Issue by gjm1128** [rpardini/docker-registry-proxy#48]
Hello, first of all, thanks for making good image and solution.

Now I'm trying to apply this good solution in my office.

And we have corporate proxy such as http://x.x.x.x:8080 and have certificates for this host.

In this situation, how can I make the changes to work nginx properly?

I tried.. 
1. update certificates
# Add company certificates
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/* \
  mkdir /usr/local/share/ca-certificates/
COPY corporate.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

2. change nginx conf
# forward proxy for non-CONNECT request
location / {
  # add_header "Content-type" "text/plain" always;
  proxy_pass http://x.x.x.x:8080;
  # return 200 "docker-registry-proxy: The docker caching proxy is working!";
}

but it doesn't work.

Please check when you have time. Thanks!

**Comment by rpardini** [comment]
Check out #62
