### ISSUE TITLE
Run `create_ca_cert.sh` as a single command

### ISSUE THREAD

**Issue by dobleme** [rpardini/docker-registry-proxy#49]
Hi, first of all, thank you for this!

I don't know much about certificates and I am not sure if what I'm gonna ask have sense.

Could be nice if `docker-registry-proxy` can be run as `docker run docker-registry-proxy create-ca-cert` restart all the necessary things and then start the proxy as usual.

What do you think? This is because I want to avoid curling the cert in a loop, stoping the service, refresh the certs and rerun the proxy again.

Thank you

**Comment by rpardini** [comment]
Hi @dobleme I'm not sure I understand your use-case, could you be more specific?
The CA certs will be created only if they don't exist (eg, on the first run).
Make sure the storage for them is correctly mapped in docker command line, check the README.
