### ISSUE TITLE
quay.io private repository and auth

### ISSUE THREAD

**Issue by rpardini** [rpardini/docker-registry-proxy#5]
```
HIT [02/Nov/2018:18:50:16 +0000] "/v2/" 401 40 "HOST:quay.io" "PROXY-HOST:quay.io" "UPSTREAM:-"
HIT [02/Nov/2018:18:50:17 +0000] "/v2/auth" 200 1063 "HOST:quay.io" "PROXY-HOST:quay.io" "UPSTREAM:-"
MISS [02/Nov/2018:18:50:18 +0000] "/v2/<repository-redacted>/<image-name-redacted>/manifests/4.2.0-8" 401 40 "HOST:quay.io" "PROXY-HOST:quay.io" "UPSTREAM:50.16.237.72:443"
```

You'll see that /v2 is a HIT (401), /v2/auth is a HIT (200) (is it supposed to cache it?), but the image itself is a MISS (401).

Docker will say: `Error response from daemon: unauthorized: authentication required`

Authentication was configured:

`Adding Auth for registry 'quay.io' with user '<redacted>'.`

Pulling from public registries obviously works just fine, as does the caching.

_Originally posted by @outworlder in https://github.com/rpardini/docker-registry-proxy/issues/1#issuecomment-435525602_

**Comment by rpardini** [comment]
I've rewritten most of the caching part. I don't know the quay.io specifics since I don't have an account there (there's no free option?)...
Anyway check out 0.2.1 if you can, it should at least behave a bit differently. Thanks

**Comment by outworlder** [comment]
@rpardini Hi, I did test with 0.2.1, but it doesn't seem to have helped. For now, I can work around this by a) not providing authentication for quay.io to the proxy and b) keeping the auth information in docker, as the header is preserved by the proxy.

**Comment by outworlder** [comment]
@rpardini Quay does have  a 'free' option (https://quay.io/signin/). There are some limitations, but this should be enough.

**Comment by outworlder** [comment]
Spoke too soon :)

```  Warning  Failed                 58s               kubelet, 172.86.112.156  Failed to pull image "quay.io/<redacted>": rpc error: code = Unknown desc = error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Expires>2018-11-15T01:40:45Z</Expires><ServerTime>2018-11-15T19:09:21Z</ServerTime></Error>"```

**Comment by rpardini** [comment]
New caching logic in `0.3.0-beta1` could fix this.

**Comment by noseka1** [comment]
@rpardini It is possible to create a private repository in Quay using the free account. You have to push an image into a repo that doesn't exist yet, for example: `podman login quay.io; podman push quay.io/noseka1/test:1`. This will create a private repository `test`.
