### ISSUE TITLE
Time out issue on any image

### ISSUE THREAD

**Issue by obedmr** [rpardini/docker-registry-proxy#6]
I'm running the registry proxy and seems like not reaching the remote registries URLs. I'm running this:

```
docker run --rm --name docker_registry_proxy -it \
       -p 0.0.0.0:3128:3128 \
       -p 8081:8081 \
       -v $(pwd)/docker_mirror_cache:/docker_mirror_cache \
       -v $(pwd)/docker_mirror_certs:/ca \
       -e REGISTRIES="k8s.gcr.io gcr.io quay.io docker.io" \
       -e AUTH_REGISTRIES="auth.docker.io:userX:passX" \
       rpardini/docker-registry-proxy
```

And then, I'm getting the following error:

```
.
.
Starting nginx! Have a nice day.
Web server listening at http://0.0.0.0:8081/
Proxy server listening at http://*:443


127.0.0.1:43248: clientconnect
127.0.0.1:43248: Certificate verification error for 127.0.0.1: self signed certificate in certificate chain (errno: 19, depth: 2)
127.0.0.1:43248: Ignoring server verification error, continuing with connection


2018/12/07 17:25:08 [error] 85#85: *3 registry-1.docker.io could not be resolved (110: Operation timed out), client: 127.0.0.1, server: _, request: "GET /v2/ HTTP/1.1", host: "registry-1.docker.io"
- [07/Dec/2018:17:25:08 +0000] "/v2/" 502 173 "HOST:registry-1.docker.io" "PROXY-HOST:registry-1.docker.io" "UPSTREAM:-"
127.0.0.1:43248: Error in HTTP connection: TcpDisconnect("(32, 'EPIPE')",)
127.0.0.1:43248: clientdisconnect
```

Any idea why it would be happening?

**Comment by StanYago** [comment]
I've got an idea and a potential fix. Are you running this behind a
firewall?

**Comment by obedmr** [comment]
@StanYago thanks for the response, yes, I'm behind a corporate firewall, I have transparent proxy configured on my machine and everything else is working fine, since it's an nginx based solution, I'm not sure if that could be the  problem.

**Comment by obedmr** [comment]
@StanYago I think I found a solution for my `behind-firewall` case, I changed the resolvers to the internal ones we use in our corporation. I basically modified this line: https://github.com/rpardini/docker-registry-proxy/blob/master/nginx.conf#L111

Were you thinking in other approach?

**Comment by StanYago** [comment]
> @StanYago I think I found a solution for my `behind-firewall` case, I changed the resolvers to the internal ones we use in our corporation. I basically modified this line: https://github.com/rpardini/docker-registry-proxy/blob/master/nginx.conf#L111
> 
> Were you thinking in other approach?

I submitted a fix here [PR#7](https://github.com/rpardini/docker-registry-proxy/pull/7)
Instead of hard coded value use DNS settings from container inside nginx.

**Comment by rpardini** [comment]
@StanYago done.
@obedmr a quick question, since other people have (mostly off-Github) asked about similar behind-firewall cases. What is your "transparent firewall" solution, specially in connection with Docker? I'd love to hear about it.

**Comment by obedmr** [comment]
@rpardini yeah, I'm using this project https://github.com/crops/chameleonsocks, it's pretty cool, all traffic is being pased by the container, even rest of containers internet traffic.

**Comment by rpardini** [comment]
Thanks @obedmr -- I assume @StanYago's patch worked, and will close this.
