### ISSUE TITLE
How to configure connecting to upstream servers via https_proxy?

### ISSUE THREAD

**Issue by askervin** [rpardini/docker-registry-proxy#62]
Is it possible to use upstream through https_proxy?

**Comment by rpardini** [comment]
Hi, this has come up before somewhere. This project is 99% nginx; if you can find a way to make nginx do it, then it should be simple to implement here. PRs welcome...

**Comment by hishamanver** [comment]
Would love this feature!

Closest thing i could find that may help is https://stackoverflow.com/questions/46803431/nginx-proxy-pass-over-https-proxy

**Comment by rpardini** [comment]
Yep. The socat "solution" is way too hackish. Until nginx itself has proper support I wouldn't mess with it.
