### ISSUE TITLE
Unable to use proxy with quay.io

### ISSUE THREAD

**Issue by Ramzec** [rpardini/docker-registry-proxy#67]
As per https://docs.quay.io/api/
```
...
The Quay.io API is a full OAuth 2, RESTful API.
...

```
Is it possible to handle the case?

**Comment by rpardini** [comment]
Hmm. This project does not use Quay's (or any other's) API directly.
It just proxies the registry path OCI.

**Comment by Ramzec** [comment]
I meant docker is unable to pull images from quay.io using the proxy. It constantly returns "authentication failed".
