### ISSUE TITLE
Unable to pull images from quay.io

### ISSUE THREAD

**Issue by Ramzec** [rpardini/docker-registry-proxy#68]
Does anyone use the proxy to access quay.io. As I understand the proxy does login, but seems something doesn't work, but cannot understand what.

**Comment by rpardini** [comment]
Hmm. Take a look at the README https://github.com/rpardini/docker-registry-proxy/blob/master/README.md (search for "quay")
Also #5 has some stuff about quay.
Please don't open duplicate issues, and add the relevant info (cmdline, logs, errors, etc)

**Comment by Ramzec** [comment]
I've checked both methods and all good:
1. run proxy without auth-info and use docker login
2. run proxy with auth-info and omit docker login

Would be nice if you can add such info to the README file.

seems that was my mistake. so I'm sorry for the noise.
