### ISSUE TITLE
Question - Is this works in airgap environment

### ISSUE THREAD

**Issue by MaheshTR033** [rpardini/docker-registry-proxy#72]
Is docker-registry-proxy works on airgap environment. Is connection to external network required even after caching the images.

I configured docker-registry-proxy with caching docker images when public interface is up.
Then, I bring down the public interface.

When requests come to docker-registry-proxy from clients, looks like it references external docker registry.
The docker pull on clients will fail.

In one of the docker url following is the description.
https://docs.docker.com/registry/recipes/mirror/

What if the content changes on the Hub?

When a pull is attempted with a tag, the Registry checks the remote to ensure if it has the latest version of the requested content. Otherwise, it fetches and caches the latest content.

Can you please clarify.

**Comment by rpardini** [comment]
I performed no tests with the proxy in an airgapped environment.
I suppose it still needs DNS to resolve, at least.
After the cache is warm, it _should_ work airgapped, but no guarantees.

**Comment by MaheshTR033** [comment]
Thank you for clarification, I updated /etc/hosts in registry docker, looks like issue is not resolved. The log messages are as follows

Starting nginx for registry proxy
2021/01/04 05:30:41 [error] 42#42: *3 registry-1.docker.io could not be resolved (110: Operation timed out), client: 127.0.0.1, server: _, request: "GET /v2/ HTTP/1.1", host: "registry-1.docker.io"
- [04/Jan/2021:05:30:41 +0000] "/v2/" 502 173 "HOST:registry-1.docker.io" "PROXY-HOST:registry-1.docker.io" "UPSTREAM:-"
2021/01/04 06:30:58 [error] 42#42: *9 registry-1.docker.io could not be resolved (110: Operation timed out), client: 127.0.0.1, server: _, request: "GET /v2/ HTTP/1.1", host: "registry-1.docker.io"
- [04/Jan/2021:06:30:58 +0000] "/v2/" 502 173 "HOST:registry-1.docker.io" "PROXY-HOST:registry-1.docker.io" "UPSTREAM:-"

**Comment by MaheshTR033** [comment]
2021/01/05 06:47:18 [warn] 37#37: *8 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /v2/ HTTP/1.1", upstream: "https://34.238.187.50:443/v2/", host: "registry-1.docker.io"
2021/01/05 06:47:18 [error] 37#37: *8 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /v2/ HTTP/1.1", upstream: "https://34.238.187.50:443/v2/", host: "registry-1.docker.io"
