### ISSUE TITLE
Insecure registry support

### ISSUE THREAD

**Issue by dom54** [rpardini/docker-registry-proxy#74]
Hi, just wondering if this can be used to proxy insecure registries.  I have tried to set it up but I get 
Error response from daemon: received unexpected HTTP status: 502 Bad Gateway

This is because its connecting to the proxy, which is trying to forward on 443 to the private registry (Docker first tries https- and goes to the proxy even though I don't have HTTPS_PROXY configured), then returns bad gateway because the upstream server doesnt have 443 enabled.  (Docker would normally retry on http , but doesnt on a 502 bad gateway - at least I think thats what the issue is)

**Comment by rpardini** [comment]
Hi, no, no support for insecure registries. Expose your registry securely *first* and then you can proxy/cache it using this project, not otherwise.

**Comment by dom54** [comment]
I've got this working with a few modifications, is it worth me following up with a PR/

**Comment by rpardini** [comment]
Nah, I won't merge, but do enjoy it!

**Comment by changdongvan** [comment]
> I've got this working with a few modifications, is it worth me following up with a PR?

Could you provide a patch at your forked repo to share your modification to support insecure registries?
