### ISSUE TITLE
Self signed certificates

### ISSUE THREAD

**Issue by rwanito** [rpardini/docker-registry-proxy#75]
Hi !
Thanks for your work !
I'm triing to set up the proxy but I can't do that because my gitlab registry is self signed (on intranet).
Nginx says me : error self signed certificate.

How can I bypass this error ?

And, is it production ready ?

Thanks !!

**Comment by rpardini** [comment]
Yes, many people are using this in production, few people are using it securely.
Please read the README, the Dockerfile, nginx.conf and entrypoint.sh, and you'll discover how to disable upstream cert verification, and hopefully realize it's a terrible idea, and just fix your gitlab cert, eg, use LetsEncrypt. Good luck.
