### ISSUE TITLE
Mounted `/etc/nginx/resolvers.conf` fails at startup

### ISSUE THREAD

**Issue by tlex** [rpardini/docker-registry-proxy#86]
Looking at [entrypoint.sh#L23](https://github.com/rpardini/docker-registry-proxy/blob/master/entrypoint.sh#L23):
```sh
if [ ! -e $confpath ] || [ "$conf" != "$(cat $confpath)" ]
```
If I use a custom file mounted under `/etc/nginx/resolvers.conf`, then the second condition will always return true.

This fails with:
```
/entrypoint.sh: line 28: /etc/nginx/resolvers.conf: Read-only file system
```

I would suggest removing the second condition, since the only use case where the file exists at that point is if the user actually mounted it there.

Thanks

**Comment by rpardini** [comment]
Absolutely.  This code was copy/pasted from non-docker code, and was terribly trying to account for "don't write the file if its contents wouldn't change". Shameful. Thanks.
