### ISSUE TITLE
Works with kind?

### ISSUE THREAD

**Issue by curtbushko** [rpardini/docker-registry-proxy#92]
Has anyone gotten this proxy to work with kubernetes kind for local development?

https://kind.sigs.k8s.io/docs/user/quick-start/

**Comment by sestegra** [comment]
@curtbushko It works well on kind as well.

Let's say you setup the proxy on host `192.168.66.72`
Launch following script after creating your cluster.

```
#!/bin/sh

KIND_NAME=${1-kind}
SETUP_URL=http://192.168.66.72:3128/setup/systemd
for NODE in $(kind get nodes --name "$KIND_NAME"); do
  echo "Configure docker-registry-proxy on $NODE"
  curl -s $SETUP_URL \
    | sed s/docker\.service/containerd\.service/g \
    | docker exec -i "$NODE" bash -
done
```

**Comment by leorolland** [comment]
@sestegra You are my hero, after trying doing for several hours, my kind cluster is finally working ! Thx !

**Comment by rpardini** [comment]
👍  I'll take PR for adding this as documentation if you'll send it.
