### ISSUE TITLE
Can we cache docker blobs by SHA

### ISSUE THREAD

**Issue by yamarane** [rpardini/docker-registry-proxy#93]
**Scenario**: 

someDockerImage1
somedockerImage2

Both have common blob

1. my.docker.host/v2/someDockerImage1/blobs/sha256:74924e75d64523f42420d9b0617430fa955e49d835e663e6c838f0ed5209c8da
2. my.docker.host/v2/someDockerImage2/blobs/sha256:74924e75d64523f42420d9b0617430fa955e49d835e663e6c838f0ed5209c8da

**Expectation**: Nginx cache should store above 2 blobs as one but it's storing as two different blobs and this causing storage issues.

How can we solve this issue?

**Comment by yamarane** [comment]
@rpardini @cpuguy83 Can you please check if it's possible?

**Comment by rpardini** [comment]
Hi @yamarane  could please send some actual images that show this problem? It's not supposed to, and if it's indeed happening it's more probably a bug in nginx than in this project. (meaning: make sure, http caching can be tricky)

**Comment by yamarane** [comment]
This worked for me

```
     location ~ ^/v2/(.*)/blobs/(.*) {
            set $cache_key $2;
            proxy_pass https://$host;
            proxy_cache cache;
            proxy_cache_key $cache_key;
            ```
